var Pokedex = [
    {
        'number':'001',
        'name' :'妙蛙种子',
        'name_jp' : 'フシギダネ',
        'name_en' : 'Bulbasaur',
        'properties' : ['草','毒'],
        'star' : 4,
    },
    {
        'number':'002',
        'name' :'妙蛙草',
        'name_jp' : 'フシギソウ',
        'name_en' : 'Ivysaur',
        'properties' : ['草','毒'],
        'star' : 4,
    },
    {
        'number':'003',
        'name' :'妙蛙花',
        'name_jp' : 'フシギバナ',
        'name_en' : 'Venusaur',
        'properties' : ['草','毒'],
        'star' : 4,
    },
    {
        'number':'004',
        'name' :'小火龙',
        'name_jp' : 'ヒトカゲ',
        'name_en' : 'Charmander',
        'properties' : ['火'],
        'star' : 4,
    },
    {
        'number':'005',
        'name' :'火恐龙',
        'name_jp' : 'リザード',
        'name_en' : 'Charmeleon',
        'properties' : ['火'],
        'star' : 4,
    },
    {
        'number':'006',
        'name' :'喷火龙',
        'name_jp' : 'リザードン',
        'name_en' : 'Charizard',
        'properties' : ['火','飞行'],
        'star' : 4,
    },
    {
        'number':'007',
        'name' :'杰尼龟',
        'name_jp' : 'ゼニガメ',
        'name_en' : 'Squirtle',
        'properties' : ['水'],
        'star' : 4,
    },
    {
        'number':'008',
        'name' :'卡咪龟',
        'name_jp' : 'カメール',
        'name_en' : 'Wartortle',
        'properties' : ['水'],
        'star' : 4,
    },
    {
        'number':'009',
        'name' :'水箭龟',
        'name_jp' : 'カメックス',
        'name_en' : 'Blastoise',
        'properties' : ['水'],
        'star' : 4,
    },
    {
        'number':'010',
        'name' :'绿毛虫',
        'name_jp' : 'キャタピー',
        'name_en' : 'Caterpie',
        'properties' : ['虫'],
        'star' : 1,
    },
    {
        'number':'011',
        'name' :'铁甲蛹',
        'name_jp' : 'トランセル',
        'name_en' : 'Metapod',
        'properties' : ['虫'],
        'star' : 1,
    },
    {
        'number':'012',
        'name' :'巴大蝶',
        'name_jp' : 'バタフリー',
        'name_en' : 'Butterfree',
        'properties' : ['虫','飞行'],
        'star' : 1,
    },
    {
        'number':'013',
        'name' :'独角虫',
        'name_jp' : 'ビードル',
        'name_en' : 'Weedle',
        'properties' : ['虫','毒'],
        'star' : 1,
    },
    {
        'number':'014',
        'name' :'鐵殼蛹',
        'name_jp' : 'コクーン',
        'name_en' : 'Kakuna',
        'properties' : ['虫','毒'],
        'star' : 1,
    },
    {
        'number':'015',
        'name' :'大针蜂',
        'name_jp' : 'スピアー',
        'name_en' : 'Beedrill',
        'properties' : ['虫','毒'],
        'star' : 1,
    },
    {
        'number':'016',
        'name' :'波波',
        'name_jp' : 'ポッポ',
        'name_en' : 'Pidgey',
        'properties' : ['一般','飞行'],
        'star' : 1,
    },
    {
        'number':'017',
        'name' :'比比鸟',
        'name_jp' : 'ピジョン',
        'name_en' : 'Pidgeotto',
        'properties' : ['一般','飞行'],
        'star' : 1,
    },
    {
        'number':'018',
        'name' :'大比鳥',
        'name_jp' : 'ピジョット',
        'name_en' : 'Pidgeot',
        'properties' : ['一般','飞行'],
        'star' : 1,
    },
    {
        'number':'019',
        'name' :'小拉达',
        'name_jp' : 'コラッタ',
        'name_en' : 'Rattata',
        'properties' : ['一般'],
        'star' : 1,
    },
    {
        'number':'020',
        'name' :'拉达',
        'name_jp' : 'ラッタ',
        'name_en' : 'Raticate',
        'properties' : ['一般'],
        'star' : 1,
    },
    {
        'number':'021',
        'name' :'烈雀',
        'name_jp' : 'オニスズメ',
        'name_en' : 'Spearow',
        'properties' : ['一般','飞行'],
        'star' : 1,
    },
    {
        'number':'022',
        'name' :'大嘴雀',
        'name_jp' : 'オニドリル',
        'name_en' : 'Fearow',
        'properties' : ['一般','飞行'],
        'star' : 1,
    },
    {
        'number':'023',
        'name' :'阿柏蛇',
        'name_jp' : 'アーボ',
        'name_en' : 'Ekans',
        'properties' : ['毒'],
        'star' : 2,
    },
    {
        'number':'024',
        'name' :'阿柏怪',
        'name_jp' : 'アーボック',
        'name_en' : 'Arbok',
        'properties' : ['毒'],
        'star' : 2,
    },
    {
        'number':'025',
        'name' :'皮卡丘',
        'name_jp' : 'ピカチュウ',
        'name_en' : 'Pikachu',
        'properties' : ['电'],
        'star' : 4,
    },
    {
        'number':'026',
        'name' :'雷丘',
        'name_jp' : 'ライチュウ',
        'name_en' : 'Raichu',
        'properties' : ['电'],
        'star' : 4,
    },
    {
        'number':'027',
        'name' :'穿山鼠',
        'name_jp' : 'サンド',
        'name_en' : 'Sandshrew',
        'properties' : ['地面'],
        'star' : 2,
    },
    {
        'number':'028',
        'name' :'穿山王',
        'name_jp' : 'サンドパン',
        'name_en' : 'Sandslash',
        'properties' : ['地面'],
        'star' : 2,
    },
    {
        'number':'029',
        'name' :'尼多兰',
        'name_jp' : 'ニドラン♀',
        'name_en' : 'Nidoran♀',
        'properties' : ['毒'],
        'star' : 2,
    },
    {
        'number':'030',
        'name' :'尼多娜',
        'name_jp' : 'ニドリーナ',
        'name_en' : 'Nidorina',
        'properties' : ['毒'],
        'star' : 2,
    },
    {
        'number':'031',
        'name' :'尼多后',
        'name_jp' : 'ニドクイン',
        'name_en' : 'Nidoqueen',
        'properties' : ['毒','地面'],
        'star' : 2,
    },
    {
        'number':'032',
        'name' :'尼多朗',
        'name_jp' : 'ニドラン♂',
        'name_en' : 'Nidoran♂',
        'properties' : ['毒'],
        'star' : 2,
    },
    {
        'number':'033',
        'name' :'尼多力诺',
        'name_jp' : 'ニドリーノ',
        'name_en' : 'Nidorino',
        'properties' : ['毒'],
        'star' : 2,
    },
    {
        'number':'034',
        'name' :'尼多王',
        'name_jp' : 'ニドキング',
        'name_en' : 'Nidoking',
        'properties' : ['毒','地面'],
        'star' : 2,
    },
    {
        'number':'035',
        'name' :'皮皮*',
        'name_jp' : 'ピッピ',
        'name_en' : 'Clefairy',
        'properties' : ['妖精'],
        'star' : 3,
    },
    {
        'number':'036',
        'name' :'皮可西*',
        'name_jp' : 'ピクシー',
        'name_en' : 'Clefable',
        'properties' : ['妖精'],
        'star' : 3,
    },
    {
        'number':'037',
        'name' :'六尾',
        'name_jp' : 'ロコン',
        'name_en' : 'Vulpix',
        'properties' : ['火'],
        'star' : 3,
    },
    {
        'number':'038',
        'name' :'九尾',
        'name_jp' : 'キュウコン',
        'name_en' : 'Ninetales',
        'properties' : ['火'],
        'star' : 3,
    },
    {
        'number':'039',
        'name' :'胖丁*',
        'name_jp' : 'プリン',
        'name_en' : 'Jigglypuff',
        'properties' : ['一般','妖精'],
        'star' : 2,
    },
    {
        'number':'040',
        'name' :'胖可丁*',
        'name_jp' : 'プクリン',
        'name_en' : 'Wigglytuff',
        'properties' : ['一般','妖精'],
        'star' : 2,
    },
    {
        'number':'041',
        'name' :'超音蝠',
        'name_jp' : 'ズバット',
        'name_en' : 'Zubat',
        'properties' : ['毒','飞行'],
        'star' : 1,
    },
    {
        'number':'042',
        'name' :'大嘴蝠',
        'name_jp' : 'ゴルバット',
        'name_en' : 'Golbat',
        'properties' : ['毒','飞行'],
        'star' : 1,
    },
    {
        'number':'043',
        'name' :'走路草',
        'name_jp' : 'ナゾノクサ',
        'name_en' : 'Oddish',
        'properties' : ['草','毒'],
        'star' : 1,
    },
    {
        'number':'044',
        'name' :'臭臭花',
        'name_jp' : 'クサイハナ',
        'name_en' : 'Gloom',
        'properties' : ['草','毒'],
        'star' : 1,
    },
    {
        'number':'045',
        'name' :'霸王花',
        'name_jp' : 'ラフレシア',
        'name_en' : 'Vileplume',
        'properties' : ['草','毒'],
        'star' : 1,
    },
    {
        'number':'046',
        'name' :'派拉斯',
        'name_jp' : 'パラス',
        'name_en' : 'Paras',
        'properties' : ['虫','草'],
        'star' : 1,
    },
    {
        'number':'047',
        'name' :'派拉斯特',
        'name_jp' : 'パラセクト',
        'name_en' : 'Parasect',
        'properties' : ['虫','草'],
        'star' : 1,
    },
    {
        'number':'048',
        'name' :'毛球',
        'name_jp' : 'コンパン',
        'name_en' : 'Venonat',
        'properties' : ['虫','毒'],
        'star' : 1,
    },
    {
        'number':'049',
        'name' :'摩魯蛾',
        'name_jp' : 'モルフォン',
        'name_en' : 'Venomoth',
        'properties' : ['虫','毒'],
        'star' : 1,
    },
    {
        'number':'050',
        'name' :'地鼠',
        'name_jp' : 'ディグダ',
        'name_en' : 'Diglett',
        'properties' : ['地面'],
        'star' : 1,
    },
    {
        'number':'051',
        'name' :'三地鼠',
        'name_jp' : 'ダグトリオ',
        'name_en' : 'Dugtrio',
        'properties' : ['地面'],
        'star' : 2,
    },
    {
        'number':'052',
        'name' :'喵喵',
        'name_jp' : 'ニャース',
        'name_en' : 'Meowth',
        'properties' : ['一般'],
        'star' : 1,
    },
    {
        'number':'053',
        'name' :'猫老大',
        'name_jp' : 'ペルシアン',
        'name_en' : 'Persian',
        'properties' : ['一般'],
        'star' : 2,
    },
    {
        'number':'054',
        'name' :'可达鸭',
        'name_jp' : 'コダック',
        'name_en' : 'Psyduck',
        'properties' : ['水'],
        'star' : 2,
    },
    {
        'number':'055',
        'name' :'哥达鸭',
        'name_jp' : 'ゴルダック',
        'name_en' : 'Golduck',
        'properties' : ['水'],
        'star' : 3,
    },
    {
        'number':'056',
        'name' :'猴怪',
        'name_jp' : 'マンキー',
        'name_en' : 'Mankey',
        'properties' : ['格斗'],
        'star' : 2,
    },
    {
        'number':'057',
        'name' :'火爆猴',
        'name_jp' : 'オコリザル',
        'name_en' : 'Primeape',
        'properties' : ['格斗'],
        'star' : 3,
    },
    {
        'number':'058',
        'name' :'卡蒂狗',
        'name_jp' : 'ガーディ',
        'name_en' : 'Growlithe',
        'properties' : ['火'],
        'star' : 2,
    },
    {
        'number':'059',
        'name' :'风速狗',
        'name_jp' : 'ウインディ',
        'name_en' : 'Arcanine',
        'properties' : ['火'],
        'star' : 2,
    },
    {
        'number':'060',
        'name' :'蚊香蝌蚪',
        'name_jp' : 'ニョロモ',
        'name_en' : 'Poliwag',
        'properties' : ['水'],
        'star' : 2,
    },
    {
        'number':'061',
        'name' :'蚊香君',
        'name_jp' : 'ニョロゾ',
        'name_en' : 'Poliwhirl',
        'properties' : ['水'],
        'star' : 2,
    },
    {
        'number':'062',
        'name' :'蚊香泳士',
        'name_jp' : 'ニョロボン',
        'name_en' : 'Poliwrath',
        'properties' : ['水','格斗'],
        'star' : 2,
    },
    {
        'number':'063',
        'name' :'凯西',
        'name_jp' : 'ケーシィ',
        'name_en' : 'Abra',
        'properties' : ['超能力'],
        'star' : 3,
    },
    {
        'number':'064',
        'name' :'勇基拉',
        'name_jp' : 'ユンゲラー',
        'name_en' : 'Kadabra',
        'properties' : ['超能力'],
        'star' : 4,
    },
    {
        'number':'065',
        'name' :'胡地',
        'name_jp' : 'フーディン',
        'name_en' : 'Alakazam',
        'properties' : ['超能力'],
        'star' : 3,
    },
    {
        'number':'066',
        'name' :'腕力',
        'name_jp' : 'ワンリキー',
        'name_en' : 'Machop',
        'properties' : ['格斗'],
        'star' : 3,
    },
    {
        'number':'067',
        'name' :'豪力',
        'name_jp' : 'ゴーリキー',
        'name_en' : 'Machoke',
        'properties' : ['格斗'],
        'star' : 3,
    },
    {
        'number':'068',
        'name' :'怪力',
        'name_jp' : 'カイリキー',
        'name_en' : 'Machamp',
        'properties' : ['格斗'],
        'star' : 3,
    },
    {
        'number':'069',
        'name' :'喇叭芽',
        'name_jp' : 'マダツボミ',
        'name_en' : 'Bellsprout',
        'properties' : ['草','毒'],
        'star' : 2,
    },
    {
        'number':'070',
        'name' :'口呆花',
        'name_jp' : 'ウツドン',
        'name_en' : 'Weepinbell',
        'properties' : ['草','毒'],
        'star' : 2,
    },
    {
        'number':'071',
        'name' :'大食花',
        'name_jp' : 'ウツボット',
        'name_en' : 'Victreebel',
        'properties' : ['草','毒'],
        'star' : 2,
    },
    {
        'number':'072',
        'name' :'玛瑙水母',
        'name_jp' : 'メノクラゲ',
        'name_en' : 'Tentacool',
        'properties' : ['水','毒'],
        'star' : 2,
    },
    {
        'number':'073',
        'name' :'毒刺水母',
        'name_jp' : 'ドククラゲ',
        'name_en' : 'Tentacruel',
        'properties' : ['水','毒'],
        'star' : 2,
    },
    {
        'number':'074',
        'name' :'小拳石',
        'name_jp' : 'イシツブテ',
        'name_en' : 'Geodude',
        'properties' : ['岩石','地面'],
        'star' : 2,
    },
    {
        'number':'075',
        'name' :'隆隆石',
        'name_jp' : 'ゴローン',
        'name_en' : 'Graveler',
        'properties' : ['岩石','地面'],
        'star' : 2,
    },
    {
        'number':'076',
        'name' :'隆隆岩',
        'name_jp' : 'ゴローニャ',
        'name_en' : 'Golem',
        'properties' : ['岩石','地面'],
        'star' : 2,
    },
    {
        'number':'077',
        'name' :'小火马',
        'name_jp' : 'ポニータ',
        'name_en' : 'Ponyta',
        'properties' : ['火'],
        'star' : 3,
    },
    {
        'number':'078',
        'name' :'烈焰马',
        'name_jp' : 'ギャロップ',
        'name_en' : 'Rapidash',
        'properties' : ['火'],
        'star' : 3,
    },
    {
        'number':'079',
        'name' :'呆呆兽',
        'name_jp' : 'ヤドン',
        'name_en' : 'Slowpoke',
        'properties' : ['水','超能力'],
        'star' : 2,
    },
    {
        'number':'080',
        'name' :'呆殼獸',
        'name_jp' : 'ヤドラン',
        'name_en' : 'Slowbro',
        'properties' : ['水','超能力'],
        'star' : 2,
    },
    {
        'number':'081',
        'name' :'小磁怪*',
        'name_jp' : 'コイル',
        'name_en' : 'Magnemite',
        'properties' : ['电','钢'],
        'star' : 3,
    },
    {
        'number':'082',
        'name' :'三合一磁怪*',
        'name_jp' : 'レアコイル',
        'name_en' : 'Magneton',
        'properties' : ['电','钢'],
        'star' : 3,
    },
    {
        'number':'083',
        'name' :'大葱鸭',
        'name_jp' : 'カモネギ',
        'name_en' : 'Farfetch',
        'properties' : ['一般','飞行'],
        'star' : 5,
    },
    {
        'number':'084',
        'name' :'嘟嘟',
        'name_jp' : 'ドードー',
        'name_en' : 'Doduo',
        'properties' : ['一般','飞行'],
        'star' : 2,
    },
    {
        'number':'085',
        'name' :'嘟嘟利',
        'name_jp' : 'ドードリオ',
        'name_en' : 'Dodrio',
        'properties' : ['一般','飞行'],
        'star' : 2,
    },
    {
        'number':'086',
        'name' :'小海狮',
        'name_jp' : 'パウワウ',
        'name_en' : 'Seel',
        'properties' : ['水'],
        'star' : 2,
    },
    {
        'number':'087',
        'name' :'白海狮',
        'name_jp' : 'ジュゴン',
        'name_en' : 'Dewgong',
        'properties' : ['水','冰'],
        'star' : 3,
    },
    {
        'number':'088',
        'name' :'臭泥',
        'name_jp' : 'ベトベター',
        'name_en' : 'Grimer',
        'properties' : ['毒'],
        'star' : 1,
    },
    {
        'number':'089',
        'name' :'臭臭泥',
        'name_jp' : 'ベトベトン',
        'name_en' : 'Muk',
        'properties' : ['毒'],
        'star' : 1,
    },
    {
        'number':'090',
        'name' :'大舌贝',
        'name_jp' : 'シェルダー',
        'name_en' : 'Shellder',
        'properties' : ['水'],
        'star' : 4,
    },
    {
        'number':'091',
        'name' :'刺甲貝',
        'name_jp' : 'パルシェン',
        'name_en' : 'Cloyster',
        'properties' : ['水','冰'],
        'star' : 4,
    },
    {
        'number':'092',
        'name' :'鬼斯',
        'name_jp' : 'ゴース',
        'name_en' : 'Gastly',
        'properties' : ['幽灵','毒'],
        'star' : 2,
    },
    {
        'number':'093',
        'name' :'鬼斯通',
        'name_jp' : 'ゴースト',
        'name_en' : 'Haunter',
        'properties' : ['幽灵','毒'],
        'star' : 2,
    },
    {
        'number':'094',
        'name' :'耿鬼',
        'name_jp' : 'ゲンガー',
        'name_en' : 'Gengar',
        'properties' : ['幽灵','毒'],
        'star' : 2,
    },
    {
        'number':'095',
        'name' :'大岩蛇',
        'name_jp' : 'イワーク',
        'name_en' : 'Onix',
        'properties' : ['岩石','地面'],
        'star' : 2,
    },
    {
        'number':'096',
        'name' :'催眠貘',
        'name_jp' : 'スリープ',
        'name_en' : 'Drowzee',
        'properties' : ['超能力'],
        'star' : 4,
    },
    {
        'number':'097',
        'name' :'引夢貘人',
        'name_jp' : 'スリーパー',
        'name_en' : 'Hypno',
        'properties' : ['超能力'],
        'star' : 4,
    },
    {
        'number':'098',
        'name' :'大钳蟹',
        'name_jp' : 'クラブ',
        'name_en' : 'Krabby',
        'properties' : ['水'],
        'star' : 1,
    },
    {
        'number':'099',
        'name' :'巨钳蟹',
        'name_jp' : 'キングラー',
        'name_en' : 'Kingler',
        'properties' : ['水'],
        'star' : 1,
    },
    {
        'number':'100',
        'name' :'霹靂電球',
        'name_jp' : 'ビリリダマ',
        'name_en' : 'Voltorb',
        'properties' : ['电'],
        'star' : 3,
    },
    {
        'number':'101',
        'name' :'頑皮雷彈',
        'name_jp' : 'マルマイン',
        'name_en' : 'Electrode',
        'properties' : ['电'],
        'star' : 3,
    },
    {
        'number':'102',
        'name' :'蛋蛋',
        'name_jp' : 'タマタマ',
        'name_en' : 'Exeggcute',
        'properties' : ['草','超能力'],
        'star' : 2,
    },
    {
        'number':'103',
        'name' :'椰蛋树',
        'name_jp' : 'ナッシー',
        'name_en' : 'Exeggutor',
        'properties' : ['草','超能力'],
        'star' : 2,
    },
    {
        'number':'104',
        'name' :'卡拉卡拉',
        'name_jp' : 'カラカラ',
        'name_en' : 'Cubone',
        'properties' : ['地面'],
        'star' : 2,
    },
    {
        'number':'105',
        'name' :'嘎啦嘎啦',
        'name_jp' : 'ガラガラ',
        'name_en' : 'Marowak',
        'properties' : ['地面'],
        'star' : 2,
    },
    {
        'number':'106',
        'name' :'飛腿郎',
        'name_jp' : 'サワムラー',
        'name_en' : 'Hitmonlee',
        'properties' : ['格斗'],
        'star' : 3,
    },
    {
        'number':'107',
        'name' :'快拳郎',
        'name_jp' : 'エビワラー',
        'name_en' : 'Hitmonchan',
        'properties' : ['格斗'],
        'star' : 3,
    },
    {
        'number':'108',
        'name' :'大舌头',
        'name_jp' : 'ベロリンガ',
        'name_en' : 'Lickitung',
        'properties' : ['一般'],
        'star' : 2,
    },
    {
        'number':'109',
        'name' :'瓦斯弹',
        'name_jp' : 'ドガース',
        'name_en' : 'Koffing',
        'properties' : ['毒'],
        'star' : 1,
    },
    {
        'number':'110',
        'name' :'双弹瓦斯',
        'name_jp' : 'マタドガス',
        'name_en' : 'Weezing',
        'properties' : ['毒'],
        'star' : 1,
    },
    {
        'number':'111',
        'name' :'獨角犀牛',
        'name_jp' : 'サイホーン',
        'name_en' : 'Rhyhorn',
        'properties' : ['地面','岩石'],
        'star' : 3,
    },
    {
        'number':'112',
        'name' :'鑽角犀獸',
        'name_jp' : 'サイドン',
        'name_en' : 'Rhydon',
        'properties' : ['地面','岩石'],
        'star' : 3,
    },
    {
        'number':'113',
        'name' :'吉利蛋',
        'name_jp' : 'ラッキー',
        'name_en' : 'Chansey',
        'properties' : ['一般'],
        'star' : 2,
    },
    {
        'number':'114',
        'name' :'蔓藤怪',
        'name_jp' : 'モンジャラ',
        'name_en' : 'Tangela',
        'properties' : ['草'],
        'star' : 2,
    },
    {
        'number':'115',
        'name' :'袋獸',
        'name_jp' : 'ガルーラ',
        'name_en' : 'Kangaskhan',
        'properties' : ['一般'],
        'star' : 2,
    },
    {
        'number':'116',
        'name' :'墨海马',
        'name_jp' : 'タッツー',
        'name_en' : 'Horsea',
        'properties' : ['水'],
        'star' : 2,
    },
    {
        'number':'117',
        'name' :'海刺龙',
        'name_jp' : 'シードラ',
        'name_en' : 'Seadra',
        'properties' : ['水'],
        'star' : 4,
    },
    {
        'number':'118',
        'name' :'角金鱼',
        'name_jp' : 'トサキント',
        'name_en' : 'Goldeen',
        'properties' : ['水'],
        'star' : 3,
    },
    {
        'number':'119',
        'name' :'金鱼王',
        'name_jp' : 'アズマオウ',
        'name_en' : 'Seaking',
        'properties' : ['水'],
        'star' : 3,
    },
    {
        'number':'120',
        'name' :'海星星',
        'name_jp' : 'ヒトデマン',
        'name_en' : 'Staryu',
        'properties' : ['水'],
        'star' : 2,
    },
    {
        'number':'121',
        'name' :'宝石海星',
        'name_jp' : 'スターミー',
        'name_en' : 'Starmie',
        'properties' : ['水','超能力'],
        'star' : 3,
    },
    {
        'number':'122',
        'name' :'魔牆人偶*',
        'name_jp' : 'バリヤード',
        'name_en' : 'Mr. Mime',
        'properties' : ['超能力','妖精'],
        'star' : 5,
    },
    {
        'number':'123',
        'name' :'飞天螳螂',
        'name_jp' : 'ストライク',
        'name_en' : 'Scyther',
        'properties' : ['虫','飞行'],
        'star' : 4,
    },
    {
        'number':'124',
        'name' :'迷唇姐',
        'name_jp' : 'ルージュラ',
        'name_en' : 'Jynx',
        'properties' : ['冰','超能力'],
        'star' : 4,
    },
    {
        'number':'125',
        'name' :'电击兽',
        'name_jp' : 'エレブー',
        'name_en' : 'Electabuzz',
        'properties' : ['电'],
        'star' : 2,
    },
    {
        'number':'126',
        'name' :'鴨嘴火獸',
        'name_jp' : 'ブーバー',
        'name_en' : 'Magmar',
        'properties' : ['火'],
        'star' : 2,
    },
    {
        'number':'127',
        'name' :'凱羅斯',
        'name_jp' : 'カイロス',
        'name_en' : 'Pinsir',
        'properties' : ['虫'],
        'star' : 2,
    },
    {
        'number':'128',
        'name' :'肯泰罗',
        'name_jp' : 'ケンタロス',
        'name_en' : 'Tauros',
        'properties' : ['一般'],
        'star' : 3,
    },
    {
        'number':'129',
        'name' :'鲤鱼王',
        'name_jp' : 'コイキング',
        'name_en' : 'Magikarp',
        'properties' : ['水'],
        'star' : 2,
    },
    {
        'number':'130',
        'name' :'暴鲤龙',
        'name_jp' : 'ギャラドス',
        'name_en' : 'Gyarados',
        'properties' : ['水','飞行'],
        'star' : 5,
    },
    {
        'number':'131',
        'name' :'拉普拉斯',
        'name_jp' : 'ラプラス',
        'name_en' : 'Lapras',
        'properties' : ['水','冰'],
        'star' : 5,
    },
    {
        'number':'132',
        'name' :'百变怪',
        'name_jp' : 'メタモン',
        'name_en' : 'Ditto',
        'properties' : ['一般'],
        'star' : 5,
    },
    {
        'number':'133',
        'name' :'伊布',
        'name_jp' : 'イーブイ',
        'name_en' : 'Eevee',
        'properties' : ['一般'],
        'star' : 3,
    },
    {
        'number':'134',
        'name' :'水伊布',
        'name_jp' : 'シャワーズ',
        'name_en' : 'Vaporeon',
        'properties' : ['水'],
        'star' : 4,
    },
    {
        'number':'135',
        'name' :'雷伊布',
        'name_jp' : 'サンダース',
        'name_en' : 'Jolteon',
        'properties' : ['电'],
        'star' : 4,
    },
    {
        'number':'136',
        'name' :'火伊布',
        'name_jp' : 'ブースター',
        'name_en' : 'Flareon',
        'properties' : ['火'],
        'star' : 4,
    },
    {
        'number':'137',
        'name' :'多邊獸',
        'name_jp' : 'ポリゴン',
        'name_en' : 'Porygon',
        'properties' : ['一般'],
        'star' : 4,
    },
    {
        'number':'138',
        'name' :'菊石兽',
        'name_jp' : 'オムナイト',
        'name_en' : 'Omanyte',
        'properties' : ['岩石','水'],
        'star' : 3,
    },
    {
        'number':'139',
        'name' :'多刺菊石兽',
        'name_jp' : 'オムスター',
        'name_en' : 'Omastar',
        'properties' : ['岩石','水'],
        'star' : 3,
    },
    {
        'number':'140',
        'name' :'化石盔',
        'name_jp' : 'カブト',
        'name_en' : 'Kabuto',
        'properties' : ['岩石','水'],
        'star' : 3,
    },
    {
        'number':'141',
        'name' :'镰刀盔',
        'name_jp' : 'カブトプス',
        'name_en' : 'Kabutops',
        'properties' : ['岩石','水'],
        'star' : 3,
    },
    {
        'number':'142',
        'name' :'化石翼龙',
        'name_jp' : 'プテラ',
        'name_en' : 'Aerodactyl',
        'properties' : ['岩石','飞行'],
        'star' : 5,
    },
    {
        'number':'143',
        'name' :'卡比兽',
        'name_jp' : 'カビゴン',
        'name_en' : 'Snorlax',
        'properties' : ['一般'],
        'star' : 5,
    },
    {
        'number':'144',
        'name' :'急冻鸟',
        'name_jp' : 'フリーザー',
        'name_en' : 'Articuno',
        'properties' : ['冰','飞行'],
        'star' : 5,
    },
    {
        'number':'145',
        'name' :'闪电鸟',
        'name_jp' : 'サンダー',
        'name_en' : 'Zapdos',
        'properties' : ['电','飞行'],
        'star' : 5,
    },
    {
        'number':'146',
        'name' :'火焰鸟',
        'name_jp' : 'ファイヤー',
        'name_en' : 'Moltres',
        'properties' : ['火','飞行'],
        'star' : 5,
    },
    {
        'number':'147',
        'name' :'迷你龙',
        'name_jp' : 'ミニリュウ',
        'name_en' : 'Dratini',
        'properties' : ['龙'],
        'star' : 4,
    },
    {
        'number':'148',
        'name' :'哈克龙',
        'name_jp' : 'ハクリュー',
        'name_en' : 'Dragonair',
        'properties' : ['龙'],
        'star' : 4,
    },
    {
        'number':'149',
        'name' :'快龙',
        'name_jp' : 'カイリュー',
        'name_en' : 'Dragonite',
        'properties' : ['龙','飞行'],
        'star' : 5,
    },
    {
        'number':'150',
        'name' :'超梦',
        'name_jp' : 'ミュウツー',
        'name_en' : 'Mewtwo',
        'properties' : ['超能力'],
        'star' : 5,
    },
    {
        'number':'151',
        'name' :'梦幻',
        'name_jp' : 'ミュウ',
        'name_en' : 'Mew',
        'properties' : ['超能力'],
        'star' : 5,
    },
];

var Pokedexcolor = {
    '草' : '#1ba50e,#2ec920',
    '冰' : '#13c6db,#57e9ff',
    '超能力' :'#dd045b,#f7478d',
    '虫' : '#889610,#b5b214',
    '地面' : '#af8a19,#d8b343',
    '电' : '#b28200,#ffd621',
    '毒' : '#752464,#9e448c',
    '飞行' : '#4381ff,#72aefc',
    '钢' : '#6d6d8a,#aaaabb',
    '格斗' : '#902918,#bb5544',
    '火' : '#c72500,#f05526',
    '龙' : '#2b1aa6,#7766ee',
    '水' : '#2b1aa6,#3088e1',
    '岩石' : '#907d2f,#a89755',
    '一般' : '#969685,#bbbbaa',
    '幽灵' : '#3d3d7c,#5f52a7',
    '妖精' : '#3d3d7c,#5f52a7',
}
